name: Publish Package to npmjs
on:
  push:
    branches: [master]

permissions:
  id-token: write  # Required for OIDC

jobs:
  publish-npm:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to npm
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - name: Setup tmate session  # 仅在失败时运行
        if: failure()  # 只在上一级步骤失败时执行
        uses: mxschmitt/action-tmate@v3
      - run: yarn npm publish // for Yarn version 1, use `yarn publish` instead
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
